### ISSUE TITLE
Add option to remove or transfer towns/claims after X days of inactivity 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTowns#10]
Suggested by Discord user: GrandpaCrunkle#3763
> Add a remove town/claims after x amount of days of player inactivity.

Adding onto this: perhaps making it a setting, allowing for it to either transfer or remove the claims and then a setting for inactivity count. The aforementioned transferring might have to be done just by pulling the member list of the town and choosing the earliest member to become the "owner".

**Comment by farum12** [comment]
Yeah, pretty please! If that process could be automated it would be pretty dope.
I'm looking forward to that feature, as it's present in Advanced Region Market and saves a lot of time for the admins. ARM is a plot plugin, which enables buying, setting their flags, etc. In the Advanced Region Market inactivity reset works like this:
- inactivity reset time is controlled via settings in config and permission groups (eg. an iron rank player's inactivity reset time is 7d and a diamond rank player's inactivity reset time is 21d); the plot will be reset when the Owner is offline for a certain amount of time;
- if the remaining time is very close to 0 (this is also settable), the member can take over the plot from the Owner; the Owner will become a member
- if nobody will prevent the remaining time by going 0, then the plot is reset, back to its original state. 

The two first points could be a part of HT, the last one - could be modified. In the HT, removing the town from its existence should be enough.
