### ISSUE TITLE
Add %husktowns_town_claims% and %husktowns_town_maxclaims% placeholders

### ISSUE THREAD

**Issue by thomasz05** [WiIIiam278/HuskTowns#103]
**Add new Placeholderapi**:

> 1.  `%husktowns_town_claims%` : This placeholder tells the number of the clams of the team in which he is the player 👍
> 
> 2. `%husktowns_town_maxclaims%` :  This placeholder tells the maximum number of the clams of the team in which he is the player 👍

**Comment by WiIIiam278** [comment]
Added in API expansion v2
