### ISSUE TITLE
Placeholder "current_location_plot_owner" not working

### ISSUE THREAD

**Issue by th3lucas** [WiIIiam278/HuskTowns#120]
the placeholder "%current_location_plot_owner%"  does not work.
the other placeholder i use work without a issue.

Placeholder Test:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/96976624/173208567-6c4ae7d5-dba3-4995-89f0-9c740aa4e2b4.png">

Placeholder Expansion Version: 1.2.2
HuskTowns Version 1.7

**Comment by WiIIiam278** [comment]
Should work in HuskTowns-Expansion v1.3.
