### ISSUE TITLE
Improve loading times

### ISSUE THREAD

**Issue by IDontKnowWhatToPutHere1** [WiIIiam278/HuskTowns#149]
HuskTowns data loading takes forever on servers with a large playerbase and lots of player and town data.

**Comment by WiIIiam278** [comment]
![image](https://user-images.githubusercontent.com/31187453/210180756-5de83788-1dfc-4a60-80f9-0c74e35c4f4f.png)
This was the big goal:tm: of the rewrite. I need to run some more serious benchmarks, but yeah, the new approach specifically targeted at claims should make their loading near instantaneous. It might take a few seconds on massive servers, but they shouldn't take 15 minutes to load a few hundred claims anymore.
