### ISSUE TITLE
Plot Trust 

### ISSUE THREAD

**Issue by IDontKnowWhatToPutHere1** [WiIIiam278/HuskTowns#151]
Plot trust does not work. If a player is assigned to a plot, they cannot plot trust another player which is unintended behavior according to the wiki's description. The plot trust and plot untrust commands only appear to work for mayor, or the roles with that command, not the player who was assigned to the chunk.

**Comment by WiIIiam278** [comment]
In 2.x plots no longer have a single assigned "owner," but rather have a single set of members. People with privileges can add these members and also set some of them as "managers" optionally who can also add their friends to the plot.
