### ISSUE TITLE
Town Disband message duplicate when crossing servers

### ISSUE THREAD

**Issue by R3voolt** [WiIIiam278/HuskTowns#184]
As title says , i create a town, change servers on network, where i have town installed, and in the moment i disband town and swap servers i get duplicate message of Town was disbanded. So after disband i join 2 more servers that i have linked, and every time i join server i get the message The town of xxx has beed disbanded!
https://gyazo.com/4dcce5fd5c38ba85e8736a5b1b3f989b

**Comment by R3voolt** [comment]
steps to reproduce , i did it on 3 servers:  /town create test on server 1, move to server 2, move to server 3, go back to server 1, disband town, and move again to server 2 and 3

**Comment by WiIIiam278** [comment]
Can't reproduce with plugin messages
