### ISSUE TITLE
%husktowns_town_color% problem

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#207]
%husktowns_town_color% returns Not in town when not in a town instead of a null color value or &r. When trying combination 
"&%husktowns_town_color%%husktowns_town_name%" to show town names with color it looks bad for people without town. 
![2023-03-29_21 29 26](https://user-images.githubusercontent.com/97362850/228697761-30a9d0db-9098-44ef-b48f-58a61466c7b8.png)
(I changed the placeholder name to "Nomad" instead of "Not in town" but behavior should be the same.

**Comment by WiIIiam278** [comment]
No you're right it should be gray (&7) iirc
