### ISSUE TITLE
(Suggestion) Add a feature to set a cost for town creation

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#211]
I think a town creation cost is very important since it works like a filter for players that join the server create a town, play a few minutes and leave forever, this will avoid having hundreds of abandoned towns in the pl storage.

**Comment by WiIIiam278** [comment]
Yeah I mean, sure, though it may also have the opposite effect if players can't make a town and decide to leave. I'd like to have some sort of automatic pruning feature available in the future.

**Comment by matipoirierg** [comment]
Agree, but I think setting a low value that makes the player grind like 8-10 minutes to get enough money is the best of both worlds.

**Comment by Xelarender** [comment]
I like this idea, and also gives a use for the money requirements for Level 1 in the levels.yml
