### ISSUE TITLE
Allowing of Placeholder Editing/Creation 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTowns#22]
> So with custom role prefixes... Provide a spot in the config that allows us to change the prefix of a resident, mayor, and trusted. For example if I put %husktowns_town_role% placeholder in my scoreboard and the player was just a resident it would obviously say "Resident". I want to be able to change to format maybe to "RESIDENT" or "[RESIDENT]".
Original Suggestion by _Seth#2764_

**Comment by WiIIiam278** [comment]
Closing this.. I don't quite know what the request was originally but I do now let you change what the placeholders return.
