### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#288]
https://spark.lucko.me/cKvX8e1a4q

**Comment by WiIIiam278** [comment]
Hello,
I'm not able to ascertain any information from the spark link attached -- there is absolutely no indication of any performance issues?
With that in mind, and no obvious errors or bugs reported in this issue, I'm going to close this and ask you open a Support Ticket and seek assistance through our Discord so we can help you further :)
