### ISSUE TITLE
Town level goes to max after server change

### ISSUE THREAD

**Issue by dodoflix** [WiIIiam278/HuskTowns#296]
Hey,

I have 3 servers 3 of them have same config, they're using HuskTown 5.2, RedisEconomy. When I'm in x server create a town, deposit then level and after that I spam deposit money and finally change my server to y server, my town level goes to the max level, current max level is 20.

HuskTown version: 5.2
Economy plugin: RedisEconomy
Server version: 1.18.2
Server distro: Purpur

**Comment by WiIIiam278** [comment]
Hello, RedisEconomy is no longer officially supported in this plugin; please upgrade to 2.5.1. Note that although the plugin isn't supported anymore, you should be able to continue using it.
Please test with both RedisEconomy and another economy like XConomy and let me know what happens when using both with the latest version (2.5.1)

**Comment by dodoflix** [comment]
> Hello, RedisEconomy is no longer officially supported in this plugin; please upgrade to 2.5.1. Note that although the plugin isn't supported anymore, you should be able to continue using it. Please test with both RedisEconomy and another economy like XConomy and let me know what happens when using both with the latest version (2.5.1)

Okey sure we'll try it, but do you have better alternative than XConomy because apparently XConomy is not up to date either. Also I don't think the bug is related to Economy plugin because economy plugin doesn't interfere with the Town level. Thank for your fast response and have a good day <3

**Comment by WiIIiam278** [comment]
> I don't think the bug is related to Economy plugin because economy plugin doesn't interfere with the Town level.
I think someone would have reported something like this before tbh, so I'm not so sure.

> Okey sure we'll try it, but do you have better alternative than XConomy because apparently XConomy is not up to date either. 
Works for me. There's a few other cross-server economy plugins that exist, though. In any case, try with both and let me know.

**Comment by dodoflix** [comment]
Hey sorry for late response, we changed economy plugin to XConomy and updated HuskTown plugin to latest (2.5.1). Sadly, after i changed all maxed out towns to level 5 after a couple minutes 3 of them already get back to level 20. So as i said it's not related to economy plugin.

**Comment by WiIIiam278** [comment]
Alright, looking into this.
