### ISSUE TITLE
gradle build fails from source

### ISSUE THREAD

**Issue by entonentoron** [WiIIiam278/HuskTowns#310]
I am on Windows and my build is failing due to 'Cannot get property 'tag' on null object'. I'm not sure what it is I am doing wrong.
full error: https://pastebin.com/NufJkkWe

**Comment by WiIIiam278** [comment]
git clone, don’t download the source zip. the build depends on the git head ref being present on disk to inject the version meta

**Comment by WiIIiam278** [comment]
uh whoops didn’t mean to close. Lmk if that works.

**Comment by entonentoron** [comment]
solved this issue, created a new one:
https://pastebin.com/nXBNDy4V
maybe also include the clone, not download release in your build instructions on Github
