### ISSUE TITLE
[BUG] Non-town members can loot armorstands

### ISSUE THREAD

**Issue by pacificminer** [WiIIiam278/HuskTowns#325]
Non-town members can take things from armor stands, including armor, weapons, and tools, even when public interact access is toggled off. We've had some thefts around the server due to this.
Husktowns 2.5.4

**Comment by WiIIiam278** [comment]
For some reason I can't quite reproduce this - but I did notice this event is currently on the INTERACT privilege.
I'm changing it to require CONTAINER access to avoid confusion, as while armor stands aren't a GUI container they are a sort of item holder.
