### ISSUE TITLE
Plugin does not restrict interact actions that take place when a player holds deactivated items

### ISSUE THREAD

**Issue by SMarc1** [WiIIiam278/HuskTowns#328]
It is possible to open a chest in a claimed area, eating a coral fruit, here I pass a video 
https://youtu.be/69keuNffYk0?si=PrvBasDlE35slgk0

**Comment by matipoirierg** [comment]
can confirm, some users on my server have been abusing these to steal stuff from other players.

**Comment by WiIIiam278** [comment]
not really sure what event I need to cancel to prevent this

**Comment by SMarc1** [comment]
lol

**Comment by WiIIiam278** [comment]
this is like such a strange issue. it seems to either not be firing (or, i'm not listeneing) to the (container) interact event during the chorus fruit cooldown

definitely a bug that ought to be filed under "how the hell did this get discovered"?

I'll work on a fix when I can though as yeah obviously this isn't good. I _think_ the act of eating chorus should be cancelled by the ender pearl event thing I added awhile back at least

**Comment by joaquinjoaco** [comment]
> "I wonder if a similar thing would happen if right clicking with an axe-deactivated shield?

Confirmed, user can open a chest when right clicking with an axe-deactivated shield.
