### ISSUE TITLE
Skript compatibility ?

### ISSUE THREAD

**Issue by Funasitien** [WiIIiam278/HuskTowns#338]
Hi! I was wondering if it will be possible to add SkriptLang compatibility to the HuskTown API, it would made this plugin 1000 better and make a difference from Towny, which has poor and quite buggy Skript compatibility.
Thanks!

**Comment by WiIIiam278** [comment]
could you elaborate on the sort of hooks script compat would need?

**Comment by Funasitien** [comment]
SkriptLAng may need additional code to link the plugin code to skript arguments and syntaxe. I found https://docs.skriptlang.org/javadocs/ on the [SkriptLang Documentation](https://docs.skriptlang.org) but it may not be enouth

**Comment by ProdPreva1l** [comment]
Making a skript extension is an entire plugin in its self.

**Comment by WiIIiam278** [comment]
Yeah I'm probably gonna say no to this one
