### ISSUE TITLE
%husktowns_current_location_plot_members% fails to return correct plot member list and can throw exceptions

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskTowns#371]
We also encountered errors when using the %husktowns_current_location_plot_members% placeholder, and PAPI testing also resulted in errors.
Reproduction method: when the plot is not specified.

When using the %husktowns_current_location_plot_members% placeholder, the returned result is incorrect (returns "Not a plot"), and PAPI testing also returns "Not a plot". However, the %husktowns_current_location_claim_type% placeholder returns normally (returns "plot").
Reproduction method: when the plot is specified, regardless of whether the plot members and administrators are set, the result is always "Not a plot".

**Comment by WiIIiam278** [comment]
I've split this issue up into two issues; #371 & #372
