### ISSUE TITLE
onMobSpawn handling slow

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#412]
Version 3.0 is lagging my server, spiking mspt pretty high and sometimes even up to 20000 stopping my server.
https://spark.lucko.me/p9JQ8mbCCr
I'll try to add more timings with higher mspt spikes if I can catch them.

**Comment by matipoirierg** [comment]
I'm pretty sure there is a memory leak somewhere there, since it's also messing with my GC, reverted to 2.6.1 and all issues were gone.

**Comment by MSCMDD** [comment]
Not only that, but the problem also caused the server creatures to be unable to reproduce.
Sheep can't have children, for example
You can't break a chicken with an egg
不仅如此，这个问题也造成了服务器生物无法生育的问题。
比如说羊无法生子
鸡蛋砸不出鸡

QAQ
