### ISSUE TITLE
Perhaps we would be better off using '⬛' and '⬜' than '█' and '▒'

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskTowns#420]
Perhaps we would be better off using '⬛' and '⬜' than '█' and '▒'
After Minecraft 1.20.1, '█' and '▒' don't seem to align
(Maybe we can determine the version of the server?)

common/src/main/java/net/william278/husktowns/map/MapSquare.java
```java
    private static final char CLAIM_CHAR = '⬛'; // private static final char CLAIM_CHAR = '█';
    private static final char WILDERNESS_CHAR = '⬜'; // private static final char WILDERNESS_CHAR = '▒';
```

也许我们使用'⬛'和'⬜'会比‘█’和'▒'更好
在Minecraft 1.20.1版本以后，‘█’和'▒'看起来并不能对齐
（也许我们可以判断一下服务器的版本？）

**Comment by WiIIiam278** [comment]
Okay let's add a config option to let this be specified
