### ISSUE TITLE
Performance regressions since v3.0

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskTowns#425]
net.william278.husktowns.libraries.cloplib.listener.BukkitEntityListener.onMobSpawn()

https://spark.lucko.me/CjPN10iyEw

**Comment by WiIIiam278** [comment]
I might just be terrible at reading spark logs but I don't see this in here. I thought I fixed this performance regression in 3.0.2!

**Comment by MSCMDD** [comment]
![image](https://github.com/WiIIiam278/HuskTowns/assets/128666602/a6a229b8-da3b-4af8-b38e-e2d0fbe0d62e)
https://spark.lucko.me/wB3awvlcPa

**Comment by ProdPreva1l** [comment]
As stated in #437 seems to be an area where we could cache some more

**Comment by MSCMDD** [comment]
> As stated in #437 seems to be an area where we could cache some more, as its filtering a stream every time the event is called (not good)

In version 2.8.9, this issue does not seem to exist

**Comment by ProdPreva1l** [comment]
Version 2.8.9??? That doesnt exist

**Comment by WiIIiam278** [comment]
Yeah it's cuz we added a flag to let you stop passive mob spawning which is slow

**Comment by MSCMDD** [comment]
> Version 2.8.9??? That doesnt exist版本2.8.9 ? ?这不存在

emmm
2.8.1？

**Comment by ProdPreva1l** [comment]
I believe this would have been added in version 3.0, was not an issue in 2.6.x

**Comment by WiIIiam278** [comment]
To summarise the issues as I understand it:
* Mob spawn checks are causing increased perf issues due to the new passive flag logic
* Stream piping seems to be expensive for some reason

**Comment by MSCMDD** [comment]
![image](https://github.com/WiIIiam278/HuskTowns/assets/128666602/dae16d27-d3bc-46e8-97f8-3c7c56416005)

**Comment by MSCMDD** [comment]
Compared to the previous version, the performance has been improved, but the performance is still very low compared to version 2.6. Perhaps an option to disable the new version's logic can be provided

**Comment by MSCMDD** [comment]
I have found that if the field of flags. yml is written incorrectly, its performance is more than double, but it seems that there is no error reported for this writing error issue

Can output an error message for the error field of flags. yml name

**Comment by MSCMDD** [comment]
I have found that if the field of flags. yml is written incorrectly, its performance will be slowed by more than half, but it seems that there is no error reported for this writing error issue

Can output an error message for the error field of flags. yml name

**Comment by MSCMDD** [comment]
I have found that if the field of flags.yml is written incorrectly, its performance will be slowed by more than half, but it seems that there is no error reported for this writing error issue


Can output an error message for the error field of flags.yml name
