### ISSUE TITLE
Allow towns to pick color rather than basing on name

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskTowns#43]
By default towns should be colored based on their name but an option should be added to let them change this to any color they want.
Involves storing town color hex code in the town table on SQL, adding to the town settings menu and adding command to handle changing it, as well as caching it in the town data cache and then updating the cache, etc.

**Comment by Iotados** [comment]
Now being Tracked as a part of the [Roadmap](https://github.com/WiIIiam278/HuskTowns/wiki/Roadmap)

**Comment by WiIIiam278** [comment]
done in v2
