### ISSUE TITLE
Is there a way to register custom child commands?

### ISSUE THREAD

**Issue by FireML** [WiIIiam278/HuskTowns#432]
I'm writing an addon plugin for my server, and would like to add a custom child to the Town command.

I've looked for a while and found nothing so I figured I'd ask here.

**Comment by WiIIiam278** [comment]
Not at present but seems like an alright API addition

**Comment by FireML** [comment]
is that something i could try to implement myself? maybe just with a simple event to listen to?

**Comment by WiIIiam278** [comment]
It probably doesn't need an event...I don't think? Can prob just expose an API method for adding it :). PRs welcome
