### ISSUE TITLE
After performing Reload on Husktown, Pl3xMap does not display Town Claim

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskTowns#438]
After performing Reload on Husktown, Pl3xMap does not display Claims
![image](https://github.com/WiIIiam278/HuskTowns/assets/128666602/82aaf375-f01f-476b-8167-35da2f7b97c7)

**Comment by WiIIiam278** [comment]
Closing as wontfix -- I listen to Pl3xMap's provided `Pl3xMapEnabledEvent` which is seemingly failing to refire on internal reload; that's a Pl3xMap issue if anything.

If you're externally reloading pl3xmap (e.g. through PlugMan), this isn't and can't be supported I'm afraid.
