### ISSUE TITLE
Flag calculations not caching and mob spawn handling causing performance issues

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#458]
https://spark.lucko.me/DkBMgfE0ye
Dropping my tps to 16 sometimes.

**Comment by WiIIiam278** [comment]
thanks for the report & timings :)

okay so:
- looks like things are much faster since release v3.0, which is good
- but huh, flag caching is not working - need to look at that.
- the mob spawn flag thing needs to be looked at in more detail by me clearly

**Comment by matipoirierg** [comment]
Hi, any plans on addresing this soon? Not trying to be pushy, just looking to get an idea when this can be solved.

**Comment by dentatar** [comment]
+1 i'm having the same issue

**Comment by matipoirierg** [comment]
> +1 i'm having the same issue

can you add me on discord? supersintiendo64
