### ISSUE TITLE
players can remove items from frames on farm chunks

### ISSUE THREAD

**Issue by matipoirierg** [WiIIiam278/HuskTowns#459]
This happens even if public build access is disabled for farm chunks.

**Comment by WiIIiam278** [comment]
so this is because Item Frames are an entity and farm chunks have `OperationType.PLAYER_DAMAGE_ENTITY` set in flags.yml

**Comment by WiIIiam278** [comment]
Marking this as works as intended, feel free to modify the flags in farm chunks to disable this.
