### ISSUE TITLE
Ender pearling inside a town you have access to is blocked due to self-damage infliction check

### ISSUE THREAD

**Issue by b01w** [WiIIiam278/HuskTowns#505]
When enderpearling anywhere after claiming a town it spams "You cant do that to playername as theyre friendly"

Also when you set players mob griefing/spawning in town rules to allow normal players to kill mobs, everytime you hit a mob it says "This chunk is claimed by townname" in chat spamming the chat which is annoying, anyway to turn this off?

Thanks :)

**Comment by WiIIiam278** [comment]
> When enderpearling anywhere after claiming a town it spams "You cant do that to playername as theyre friendly"

This is unintentional :)

> Also when you set players mob griefing/spawning in town rules to allow normal players to kill mobs, everytime you hit a mob it says "This chunk is claimed by townname" in chat spamming the chat which is annoying, anyway to turn this off?

This isn't :)
