### ISSUE TITLE
Add option to require claim adjacency 

### ISSUE THREAD

**Issue by zReport02** [WiIIiam278/HuskTowns#71]
Hi, the classic Towny plugin has a claim / unclaim bug!

In the towny plugin normally you can only claim chunks next to other claimed chunks!

But by unclaiming it is possible to leave chunks totally detached from other chunks and therefore scattered around the world depending on how users behave!

How does it work on HuskTowns?

**Comment by justaureus** [comment]
You could do it similarly to how Towny has their outposts.  Outposts could be claimed everywhere but towns can only claim adjacent to one another (with a config option to turn this on and off).

**Comment by WiIIiam278** [comment]
Something similar to be added in 1.8 -- an option to prevent making claims too close to another.
