### ISSUE TITLE
Issues with Bluemap's Integration

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskTowns#80]
Please refer to Ticket-0141 for full conversation and crash.txt.

> I recently made the switch from Pl3xmap to Bluemap... When the "map" section is set to "true" and "bluemap" in the config, the server refuses to launch. When I disable the map section in the config, the server also crashes, but only when Bluemap begins rendering the world.
> seems to be some sort of issue with Husktowns attempting and failing to send marker data to Bluemap,

**Comment by Iotados** [comment]
**Potential Replication Steps** 

1. New Server with Pl3xmap as default integration
2. Migrate to Bluemap
3. Ensuring that the map section is set to "true" and that it is set to "bluemap" in the config. Start the server.

**Comment by WiIIiam278** [comment]
This needs reproducing

**Comment by WiIIiam278** [comment]
Closing, awaiting further reproduction evidence and more details
